dist: bionic
language: java
before_install:
- rm ~/.m2/settings.xml
jdk:
- openjdk11
install: mvn -v
script: mvn -B -nsu verify jacoco:report
cache:
  directories:
  - "$HOME/.m2"
branches:
  except:
  - "/^release\\/.*$/"
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  slack:
    secure: mDuvBTUY6L4j0c6j4ELGFzll0MM6i+1AfaEdC2+GBumtPazKKm7ObK1kYIoiBSgDfAEivPUNxdoHIWgsuBnHejgEo7NAIlie4mJsJ4Ch9IIVer75Po/ZCKEIYMgPdl3nyPYDSpyQx+fBSqj3N8ncxi4Og3ImBmox7WupPr7spJ7XswT0RHxBYsA4m9ZGFSnTe2Rda7+o+F0lq7L7xiOpD0fOJwZ6MxKEN7vlV0Vvt3RdZ1LxPJGp1eF0/6lUnTZ1nmL84cWQ3t/g+au3KDnvkRiFx0CRCHQvQvFOmatCSUWKtmRETFZbdApZdrrkwsaGqiaGQVdhnQr7x4kf6iR4uM79rqmvZjxxozipb12z3EN8doCf0FZ7W2pULmX7FDPm2g3baK52QXHx/iS38ODZNzXZVGd6z51pcgWRJs/9UI/X+Bqs5IpJqN1BZMSwWNxwSlnCApDcE0FTCFjNZKj3mDraAT+lYtq+XuqiQ4+j0maN0xy/DAUdNHrG+/4dA38+/AA274LkJkvOVeBcUEkHGZevlmdEoEXOCcmrLzFb5k63JZVSKduWsZNZpSszTEsoT5BmapQP2BIkPkXSTkhP60DTuKNy8W1jpYsEKxZDUD3CBwLyTMw6DqOlnqMzBYYc+dHAvt6kKuZmzBELwjAi+3uFL4BTTmV9BnpBDARKOzk=
